name: Open Civic Data
markdown: redcarpet
pygments: true
debug: false
ga_key: UA-22821126-40
subscribe_url: "//sunlightfoundation.com/mailinglist/subscribe/"
exclude: ['opencivicdata.org.sublime-project', 'opencivicdata.org.sublime-workspace', 's3_website.yml']
