---
- name: Install data.opencivicdata.org
  hosts: opencivicdata-data
  user: ubuntu
  sudo: yes
  roles:
    - role: common-roles/common
      hostname: ocdapi
      extra_packages:
        - libpq-dev
        - unzip
        - gdal-bin
    - role: common-roles/ebs
      device_letter: k
      volume_size: 5
      ebs_path: /projects/data.opencivicdata.org/
    - role: common-roles/django
      project_name: data.opencivicdata.org
      git_repositories:
          - repo: "git://github.com/opencivicdata/data.opencivicdata.org.git"
            dir: data.opencivicdata.org
      wsgi_module: data.wsgi:application
      django_environment: {}
    - role: data
      project_name: data.opencivicdata.org
